### ISSUE TITLE
Suggested API changes

### ISSUE THREAD

**Issue by fregante** [gorillatron/async-task#3]
- Make it re-runnable by default
  - Reuse an existing worker if `keepAlive` or `worker` were supplied
  - Create a new worker every time the task is executed
- [Avoid `new`](http://stackoverflow.com/a/383503/288906), use a simple closure and return a function so it can be used effortlessly and transparently.

Current:

``` js
var AsyncTask = require( 'async-task' )

var task = new AsyncTask({
  doInBackground: (a, b) -> a + b
})

task.execute(1, 2)
  .then(function( result ) {
    result === 3
  })
  .catch( handleException )
```

Suggested:

``` js
var makeAsync = require( 'async-task' )

var sumAsync = makeAsync((a, b) -> a + b, options)

sumAsync(1, 2)
  .then(function( result ) {
    result === 3
  })
  .catch( handleException )

// also:
sumAsync.setWorker(newWorker)
sumAsync(3, 10) // call as many times as needed, like you'd expect from a function
```

**Comment by gorillatron** [comment]
Those changes makes sense. Pull request is welcomed ;) Along with tests ofc.
